version: '3.8'

services:
  secureflow-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    container_name: secureflow-app-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080/api
      - CHOKIDAR_USEPOLLING=true
    networks:
      - secureflow-dev-network
    volumes:
      - .:/app
      - /app/node_modules
      - dev-logs:/var/log
    depends_on:
      - postgres-dev
      - redis-dev
    labels:
      - "com.secureflow.environment=development"
      - "com.secureflow.service=frontend"

  postgres-dev:
    image: postgres:15-alpine
    container_name: secureflow-postgres-dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: secureflow_dev
      POSTGRES_USER: secureflow_dev
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    networks:
      - secureflow-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U secureflow_dev -d secureflow_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-dev:
    image: redis:7-alpine
    container_name: secureflow-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-dev-data:/data
    networks:
      - secureflow-dev-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: secureflow-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@secureflow.local
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - secureflow-dev-network
    depends_on:
      - postgres-dev

volumes:
  postgres-dev-data:
  redis-dev-data:
  dev-logs:
  pgadmin-data:

networks:
  secureflow-dev-network:
    driver: bridge
