[build]
builder = "nixpacks"
buildCommand = "npm install --force && npm run build"

[deploy]
startCommand = "npx serve dist -s -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
NODE_ENV = "production"
VITE_APP_NAME = "SecureFlow Automaton"
VITE_APP_VERSION = "1.0.0"
