apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
    version: 1
    readOnly: false

  - name: API Monitoring
    type: prometheus
    access: proxy
    url: http://api-monitoring:3002/metrics
    isDefault: false
    editable: true
    jsonData:
      timeInterval: 30s
      queryTimeout: 30s
      httpMethod: GET
    version: 1
    readOnly: false
