// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://kzkbrldwxvpvgvtklqis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6a2JybGR3eHZwdmd2dGtscWlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5NDE3MzIsImV4cCI6MjA1MTUxNzczMn0.eJYCfYKhDnhErlKdHFpkLLJNhEQdF4R7tgM3m9xOjqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);