apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s

    rule_files:
      - /etc/prometheus/rules/*.rules

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - alertmanager.monitoring:9093

    scrape_configs:
      # SecureFlow Automaton Application
      - job_name: 'secureflow-automaton'
        scrape_interval: 5s
        scrape_timeout: 3s
        static_configs:
          - targets: ['secureflow-automaton.secureflow-automaton:8080']
        metrics_path: '/metrics'
        relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):\d+'
            target_label: instance
            replacement: '${1}'

      # Kubernetes API Server
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https

      # Kubernetes Nodes
      - job_name: 'kubernetes-nodes'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics

      # Kubernetes Pods
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

      # Kubernetes Services
      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            action: replace
            regex: (https?)
            target_label: __scheme__
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_name

      # Istio Service Mesh Metrics (if Istio is enabled)
      - job_name: 'istio-mesh'
        scrape_interval: 15s
        static_configs:
          - targets: ['istiod.istio-system:15014']
        scheme: https
        tls_config:
          ca_file: /etc/istio/certs/root-cert.pem
          cert_file: /etc/istio/certs/cert-chain.pem
          key_file: /etc/istio/certs/key.pem
          insecure_skip_verify: true

      # Envoy Proxy Metrics (through Istio)
      - job_name: 'envoy-stats'
        metrics_path: /stats/prometheus
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "15090"
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod_name

  rules.yml: |
    groups:
      - name: secureflow.rules
        rules:
          # Application Health Rules
          - alert: SecureFlowDown
            expr: up{job="secureflow-automaton"} == 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "SecureFlow Automaton is down"
              description: "SecureFlow Automaton has been down for more than 5 minutes."

          - alert: SecureFlowHighCPU
            expr: rate(container_cpu_usage_seconds_total{pod=~"secureflow-automaton-.*"}[5m]) > 0.8
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage on SecureFlow Automaton"
              description: "CPU usage is above 80% for more than 10 minutes."

          - alert: SecureFlowHighMemory
            expr: container_memory_usage_bytes{pod=~"secureflow-automaton-.*"} / container_spec_memory_limit_bytes > 0.9
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage on SecureFlow Automaton"
              description: "Memory usage is above 90% for more than 5 minutes."

          # API Response Time Alerts
          - alert: SecureFlowSlowResponse
            expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="secureflow-automaton"}[5m])) > 5
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "Slow API response time"
              description: "95th percentile response time is above 5 seconds."

          # Error Rate Alerts
          - alert: SecureFlowHighErrorRate
            expr: rate(http_requests_total{status=~"5..", job="secureflow-automaton"}[5m]) / rate(http_requests_total{job="secureflow-automaton"}[5m]) > 0.05
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "High error rate on SecureFlow Automaton"
              description: "Error rate is above 5% for more than 5 minutes."

          # Database Connection Alerts
          - alert: SecureFlowDBConnectionIssues
            expr: increase(secureflow_db_connection_errors_total[5m]) > 10
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Database connection issues"
              description: "More than 10 database connection errors in 5 minutes."

          # Security Alerts
          - alert: SecureFlowFailedAuthentications
            expr: increase(secureflow_auth_failures_total[5m]) > 20
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High number of authentication failures"
              description: "More than 20 authentication failures in 5 minutes."

          # Quantum Service Alerts
          - alert: SecureFlowQuantumServiceDown
            expr: up{job="secureflow-automaton", service="quantum"} == 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Quantum service is down"
              description: "Quantum computing service has been down for more than 5 minutes."
