apiVersion: v1
kind: ServiceAccount
metadata:
  name: secureflow-service-account
  namespace: secureflow-automaton
  labels:
    app.kubernetes.io/name: secureflow-automaton
    app.kubernetes.io/component: service-account
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secureflow-pod-reader
  namespace: secureflow-automaton
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secureflow-pod-reader-binding
  namespace: secureflow-automaton
subjects:
- kind: ServiceAccount
  name: secureflow-service-account
  namespace: secureflow-automaton
roleRef:
  kind: Role
  name: secureflow-pod-reader
  apiGroup: rbac.authorization.k8s.io
