// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znubqwefuxqkzjgtrdcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpudWJxd2VmdXhxa3pqZ3RyZGNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjMyNjAsImV4cCI6MjA2NTM5OTI2MH0.ZWAaEm6o5_mmpn_0LNP7iowAXzTehSlDp0Opw-t7m7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);