apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: secureflow-automaton-dev

# Inherit from base
bases:
  - ../../base

# Environment-specific labels
commonLabels:
  environment: dev
  app.kubernetes.io/version: dev-latest

# Namespace override
namespace: secureflow-automaton-dev

# Environment-specific ConfigMaps
configMapGenerator:
  - name: secureflow-automaton-config
    behavior: replace
    literals:
      - ENVIRONMENT=development
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - METRICS_ENABLED=true
      - TRACING_ENABLED=false
      - MAX_WORKERS=2
      - CACHE_TTL=300
      - RATE_LIMIT_MAX=500
      - QUANTUM_FEATURES_ENABLED=false
      - BUILD_INFO=kustomize-dev

# Environment-specific Secrets
secretGenerator:
  - name: secureflow-automaton-secrets
    behavior: replace
    literals:
      - jwt-secret=dev-jwt-secret-key-12345
      - session-secret=dev-session-secret-key-12345
      - sonar-token=dev-sonar-token-placeholder
      - snyk-token=dev-snyk-token-placeholder
    type: Opaque

# Development-specific patches
patchesStrategicMerge:
  - deployment-dev.yaml
  - service-dev.yaml

# Replica count for dev
replicas:
  - name: secureflow-automaton
    count: 2

# Image for dev
images:
  - name: secureflow-automaton
    newTag: dev-latest
