name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run dependency audit
        run: npm audit --audit-level=moderate --json > npm-audit-results.json || true

      - name: Run security lint
        run: |
          npx eslint . --ext .ts,.tsx --config .eslintrc.security.cjs --format json --output-file eslint-results.json || true

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-reports
          path: |
            npm-audit-results.json
            eslint-results.json

  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type checking
        run: npm run type-check

      - name: Lint code
        run: npm run lint

      - name: Run tests with coverage
        run: npm run test:coverage || npm run test

      - name: Build for production
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
